struct BUTTON mainMenuExitButton = {	.x = 64,
					.y = 64,
					.w = 128,
					.h = 16,
					.fillColor = {255, 255, 255, 255},
					.textColor = {0, 0, 0, 255},
					.text = "EXIT APP",
					.textFontSize = 24,
					.pressed = false,
					.anchor = LR,
					.counter = 0,
					.wasPressed = false,
};
